ktor:
  deployment:
    port: "$HTTP_PORT:8080"
  application:
    modules:
      - ch.healthwallet.web.ApplicationKt.module
services:
  issuer: "$ISSUER_URL:https://issuer.healthwallet.li"
  verifier: "$VERIFIER_URL:https://verifier.healthwallet.li"
db:
  url: "$DB_URL:jdbc:postgresql://localhost:5432/healthssi_pis"
  driver: "$DB_DRIVER:org.postgresql.Driver"
  user: "$DB_USER"
  password: "$DB_PASSWORD"
  medrefdata: "$DB_MEDREFDATA:server/src/main/resources/refdata/Articles_ALL_ALL_20240429170557.xml"
